### ISSUE TITLE
Tela de Cadastro

### ISSUE THREAD

**Issue by sortega22** [sortega22/appAgendamento#2]
Pop-up da Tela de Cadastro
Link XD: 

Seleção de Participante com Radio Button: **Aluno** ou **Não Aluno**

![Image](https://user-images.githubusercontent.com/91912900/183729205-56f49743-9afa-42d4-b5b0-d9679fd9e78c.png)

**Todos os campos são obrigatórios**

- [ ] Nome Completo
- [ ] Celular (DDD+Numero) Eg. 011959678074
- [ ] email (validar email)

**Aluno**
Exibir o campo para preenchimento do **Número de Matricula**

![Image](https://user-images.githubusercontent.com/91912900/183729538-fb54b9f1-3524-49c0-a2d0-69094b87cdb6.png)

**Regra de preenchimento**

- [ ] 12 posições numéricas
- [ ] Adicionar uma regra para bloquear os caracteres abaixo 

Bloquear matrículas com os seguintes números: 
123456789012
987654321012
111111111111
222222222222
333333333333
444444444444
555555555555
666666666666
777777777777
888888888888
999999999999
000000000000
010101010101
121212121212
